### ISSUE TITLE
Change PGN source from C to XML

### ISSUE THREAD

**Issue by keesverruijt** [canboat/canboat#1]
The PGN database would be more useful and easier to maintain if it was already in XML with a proper DTD.
This would be accompanied with an XSL file to generate C code; the C analyzer should not depend on XML libraries but a compile time generation is fine.

**Comment by chgans** [comment]
Why not use the KCD format? https://github.com/julietkilo/kcd
Which is an open source alternative to http://socialledge.com/sjsu/index.php/DBC_Format
Other formats can be found here: https://github.com/ebroecker/canmatrix

**Comment by chgans** [comment]
As well this tool is pretty cool:
https://cantools.readthedocs.io/en/latest/

**Comment by jonross09** [comment]
There is a "bug" in the json file. Any PGN w/ only 1 field has an extra "Field" encapsulation. Like for isoRequest :

```
  {
        "PGN":59904,
        "Id":"isoRequest",
        "Description":"ISO Request",
        "Complete":true,
        "Length":3,
        "RepeatingFields":0,
        "Fields":{
          "Field":{
            "Order":1,
            "Id":"pgn",
            "Name":"PGN",
            "BitLength":24,
            "BitOffset":0,
            "BitStart":0,
            "Type":"Integer",
            "Resolution":1,
            "Signed":false}}},
      ```

**Comment by keesverruijt** [comment]
This is being continued else where, in issues #281 and #283.
