### ISSUE TITLE
PGN 128259

### ISSUE THREAD

**Issue by ttlappalainen** [canboat/canboat#100]
According to my tests Field 4 "Speed Water Referenced Type" is 1 byte length. E.g. Airmar sensor send 0x00 for "Water referenced". If the field would be 4 bit, it should send 0xf0. Also NMEA Reader shows on that point 0 and for value 0xf0 240. 

There is also new field 5:
4 bits, "Speed direction". It is not yet clear for me, what that means.

**Comment by canboat** [comment]
Thanks Timo...
