### ISSUE TITLE
Instance fields

### ISSUE THREAD

**Issue by ttlappalainen** [canboat/canboat#108]
Definitions has instance fields with different names like acInstance, switchBankInstance, temperatureInstance. In abtract handling all messages having instance field and different value on it are different messages. Since one device can send e.g. several temperature messages e.g. 130316, they comes from same source. There should be some common indicator that some field is instance field.

**Comment by keesverruijt** [comment]
Good plan.

**Comment by sbender9** [comment]
Ugh. This change is breaking anything that used the old names. Major headache!
