### ISSUE TITLE
Problem with "analyzer" when running cross compiled to OpenWRT MIPS (big endian)

### ISSUE THREAD

**Issue by captcha1** [canboat/canboat#111]
I cross compiled canboat to OpenWRT, and analyzer returns incorrect results : 

echo 2016-02-28T19:57:02.480Z,2,129025,33,255,8,eb,85,63,08,c8,b5,ab,db | ./analyzer

2016-02-28T19:57:02.480Z 2  33 255 129025 Position, Rapid Update:  Latitude = -147566441688.3081360; Longitude = -429.4967296

The correct result is : 

2016-02-28T19:57:02.480Z 2  33 255 129025 Position, Rapid Update:  Latitude = 14.0740075; Longitude = -60.9503800

I suspect an "endian" issue.

BTW, cross compiling is easy, just set $CC before running make : 

export CC=${CROSS_COMPILE}gcc

... I've attached a script to that downloads the OpenWRT cross compilers and sets $CROSS_COMPILE

[owrt-mips_24kc.txt](https://github.com/canboat/canboat/files/1714720/owrt-mips_24kc.txt)

**Comment by captcha1** [comment]
Oops ... attached the script

[owrt-mips_24kc.txt](https://github.com/canboat/canboat/files/1714717/owrt-mips_24kc.txt)

**Comment by keesverruijt** [comment]
Should be fixed now.
