### ISSUE TITLE
Some PGN #s have multiple definitions in XML file

### ISSUE THREAD

**Issue by jonross09** [canboat/canboat#119]
Maybe this isn't a bug? In which case how do you know which definition to use?

all of the following PGN #s have at least one dupe in the XML file. Most of them many more than 1. typically 4-5 different <PGNInfo>'s w/ the same <PGN>

60416
61184
65285
126208
126720
129808
130816
130820
130842
130845
130850

**Comment by sbender9** [comment]
This is not a bug, these PGNs can have different contents.

**Comment by jonross09** [comment]
ahh. Good to know. ok.

How do you know which one to use for any given packet? Or is that vendor specific?

**Comment by jonross09** [comment]
Very good to know. Thanks!
