### ISSUE TITLE
NMEA 0183 to NMEA 2000 conversion

### ISSUE THREAD

**Issue by jcdocka** [canboat/canboat#132]
Hi, 

Is there any way (or code in canboat) to convert nmea 0183 messages to nmea 2000 pgn's?

**Comment by sbender9** [comment]
Canboat can't do it, but take a look at SignalK(signalk.org) and the SignalK Node Server: https://github.com/SignalK/signalk-server-node

Using the signalk-to-nmea2000 plugin, it can do some conversions to 0183. New conversions can easily be added.
