### ISSUE TITLE
Command Line Utility to summarize which PGNs are available

### ISSUE THREAD

**Issue by shantanoo-desai** [canboat/canboat#139]
As a CLI thing, would it make sense to create a script to tabularize all the PGNs and Summaries to STDOUT as to see which PGNs are actually available?

Is there already something existing, something in the pipeline and desirable?

Would love to contribute to the repo.

**Comment by woobagooba** [comment]
On Jan 5, 2019, at 9:36 AM, Shan Desai <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #139<https://github.com/canboat/canboat/issues/139>.
