### ISSUE TITLE
It's not possible to discern which datagrams are framed as Fast Packets

### ISSUE THREAD

**Issue by ksltd** [canboat/canboat#144]
It is presently not possible to discern whether a datagram is to be framed as a Fast Packet from the attributes provided. This could be a bug in the data provided for certain datagrams, or it could be an oversight; it's not possible to tell which.

I had thought that the combination of Length and Repeating Fields could be used to differentiate the required framing. However, looking at 127502, this doesn't work. Perhaps the problem here is that 127502 should be represented in the manner of 127501 as both 127501 and 127502 are framed as single CAN messages with a two-bit field that is repeated 28 times; why they are represented differently escapes me. If the intention is that any message with Repeating Fields is always sent using the Fast Packet framing, then several datagram definitions need to be repaired, including 127502.

That notwithstanding, my own opinion is that:
- Length should be either an integer in the range 8…223 or 0 to indicate the length is variable.
- A new tag, Datagram Framing, should be added with two keyword values:  Single Message, the default; and Fast Packet

**Comment by keesverruijt** [comment]
Sorry, took a while to get back to you on this. The fact whether a PGN is fast-packet or single-frame is decided by the PGN number. Any PGN over 0xFFFF is fast-packet, all below are single frame. 

This is noted in the software but it is admittedly somewhat hidden:

    $ grep 'PGN range' analyzer/pgn.h
    /* PDU1 (addressed) single-frame PGN range 0E800 to 0xEEFF (59392 - 61183) */
    /* PDU1 (addressed) single-frame PGN range 0EF00 to 0xEFFF (61184 - 61439) */
    /* PDU2 non-addressed single-frame PGN range 0xF000 - 0xFEFF (61440 - 65279) */
    /* PDU1 (addressed) fast-packet PGN range 0x10000 to 0x1EEFF (65536 - 126719) */
    /* proprietary PDU1 (addressed) fast-packet PGN range 0x1EF00 to 0x1EFFF (126720 - 126975) */
    /* PDU2 (non addressed) fast packet PGN range 0x1F000 to 0x1FEFF (126976 - 130815) */
    /* proprietary PDU2 (non addressed) fast packet PGN range 0x1FF00 to 0x1FFFF (130816 - 131071) */

Does this help?

**Comment by ksltd** [comment]
Does it help? Unfortunately not, primarily because I do not believe it's correct.

You write that "any PGN over FFFF is fast-packet, all below are single-frame", which is not true. Consider the following, each over FFFF and all single-frame:
- 1F200 - Engine Parameters Rapid Update
- 1F20E - Switch Bank Control
- 1F20D - Switch Bank Status
- 1F211 - Fluid Level
- 1F214 - Battery Status

I'm sure there are many more - this list is based only upon those for which I have encountered on my own.

Your response also begs the question of the remaining part of the ID encoding space.
- 00000…0E7FF: 232 encodings in PDU1 format
- 0FF00…0FFFF: 256 encodings in PDU2 format

I'm afraid I remain confused.
