### ISSUE TITLE
An extra value in "GNSS type" used in several AIS pgns

### ISSUE THREAD

**Issue by larsujensen** [canboat/canboat#158]
The enumerated field "GNSS type" in at least PGNs 129041, 129793 and 129794 has enumerated values from 0-9 in canboat. In https://www.navcen.uscg.gov there is an extra value:
15 = internal GNSS. 9 -14 are not used.
Note, PGN 129040 also has GNSS type, but in the link number 15 is stated as unused for message 19.

**Comment by keesverruijt** [comment]
Hi, these fields are 4 bit unsigned integers in NMEA 2000. As with any (unsigned) integer the highest 2 values have a specific meaning. In the case of a 4 bit unsigned integer, these are:
14 = Error
15 = Unknown

This is already taken care of by the generic print code.
