### ISSUE TITLE
NMEA 2000: PGN 127489 (Engine Parameters, Dynamic)

### ISSUE THREAD

**Issue by john993** [canboat/canboat#176]
Hi everyone,
Sorry maybe my question is out of topic, but it is have relation with NMEA and CAN boat.

I have question, how to get the **Engine Percent Load** with this data:

CAN Identifier  DLC   D0...1... 2... 3...4... 5...6...D7
166855062          8     00  1a 00  ff  ff   ff   ff  89
166855062          8     01  71 a4 0b 00 00 5e 7a
166855062          8     02  02 00  ff  ff   ff   ff  ff
166855062          8     03  00 00 00 00 00  ff  ff

I look at PGN Explorer, the bit offset is 192 bit, but the data I got from CAN is only 8 byte (64 bit).

I can get **Temperature** data because the offset is 40 bit, but I can't get **Engine Percent Load** because the offset is 192 bit.

Thanks in advance.

**Comment by keesverruijt** [comment]
Hi John,

The PGN is a Fast Packet PGN, so they all belong together. There are various places where canboat pulls these back together into a single message.

As you can see the first packet has the first byte 00 followed by 1A. This means: this is the first packet (=00) and the total length is 0x1A bytes. The 6 following bytes are the first 6 content bytes. The remaining packets have 7 content bytes each.

The `candump2analyzer` program doesn't bother with any of this, but `analyzer` does. It recognises the format as one that is `MULTIPACKET_SEPARATE` and reformats the entire message before decoding it.

**Comment by snnszgzl** [comment]
Hi, also i have same question,
![09F10213](https://github.com/canboat/canboat/assets/38780242/80be354b-85b8-4587-8a5b-6d6049eacfd3)
picture is show PNG 127489 messages. How can i read Engine Load Percent from here ?

**Comment by keesverruijt** [comment]
Please don't hijack (closed) issues, this is not a forum. See new issue.
