### ISSUE TITLE
Visualising data

### ISSUE THREAD

**Issue by coconha2** [canboat/canboat#201]
Hi, I have good experience with CAN bus and I am now very interested in NMEA2000. I have a boat with a B&G network and am learning how it works and would like to potentially build a couple of devices for it. This is great project, congratulations!

I just started using Analyzer and was wondering which tool is used to visualise data such as this plot: https://github.com/canboat/canboat/issues/148

**Comment by sbender9** [comment]
You should check out Signal K (www.signalk.org) and the Server: https://github.com/SignalK/signalk-server-node

This uses canboat (canboatjs) under the hood. There you can use use influxdb to store history and then visualize it with Grafana: http://openplotter.wikidot.com/grafana

**Comment by sbender9** [comment]
And then join on on slack if you need any help: http://slack-invite.signalk.org/

**Comment by coconha2** [comment]
Hi Scott, 
I just joined signalk on slack. I had some issues installing signalk on my Ubuntu PC yesterday, but I was little on time. I will give it another shot this weekend.
Thanks for the pointers!
