### ISSUE TITLE
Changing license to Apache 2.0

### ISSUE THREAD

**Issue by keesverruijt** [canboat/canboat#225]
Given how the world has changed, and we're running into (small, perceived) licensing issues with SIgnal K, which uses CANboatJS which uses the JSON file, I want to change the license for (at least) the JSON file, but I'd rather change the license for the entire project.

The proposed new license is Apache 2.0 -- https://www.apache.org/licenses/LICENSE-2.0.html

I will add a message and ping all contributors to the project. Please react if you agree to have your contributions carried over, or not. If not, please PM me and we can figure out what to do with your code.

I will not change the license before March 1, 2021 to give you time to think.

**Comment by keesverruijt** [comment]
Assignees doesn't work -- let's just ping you guys?

@sbender9
@sbender9 @acolomb
@timmathews
@jpilet
@jncarter123
@chacal
@cmotelet
@saxofon
@mairas
@webmasterkai
@jonross09
@htool
@fabdrol
@e-sailing
@kledom
@cbatson
@bioffe01

**Comment by acolomb** [comment]
I'm fine with the change of license.

**Comment by kraj** [comment]
I am fine with changing the License to Apache-2.0

**Comment by keesverruijt** [comment]
Thanks @acolomb and @kraj, 

Assigning doesn't work, pinging the remaining contributors:

@bioffe01
@cbatson
@chacal
@cmotelet
@e-sailing
@fabdrol
@francois-berder
@gobenb
@htool
@jeronimo
@jlaba
@jncarter123
@jonross09
@jpilet
@kledom
@larsujensen
@lfrancois
@lgelo
@mairas
@ph1l
@pi
@sailoog
@saxofon
@sbender9
@timmathews
@tjkurki
@tkurki
@webmasterkai
@woobagooba
@zubenubi

**Comment by timmathews** [comment]
I agree to changing the license to Apache-2.0

**Comment by jeronimo** [comment]
Agreed. I guess everyone who gives a 👍 agrees as well.

**Comment by jonross09** [comment]
👍

**Comment by sailoog** [comment]
Agree

**Comment by jpilet** [comment]
Approved, very nice change.

**Comment by tkurki** [comment]
Approved 👍

**Comment by kledom** [comment]
👍

**Comment by tjkurki** [comment]
Approved - why on earth did I ever use a separate account for something here, as this is me Teppo also.

**Comment by lgelo** [comment]
👍 Agree.

**Comment by htool** [comment]
Agree 👍

**Comment by cbatson** [comment]
Works for me 👍 Presumably the license change cannot be retroactive? I.e. earlier revisions are still subject to the former license?

**Comment by sbender9** [comment]
@cbatson I think you're right, but I don't think it matters if it's retroactive in this case. Only if someone here would try to enforce the GPL on people using older versions. Clearly that is not the intention going forward.

**Comment by mairas** [comment]
This is a great change! Wholeheartedly agree.

**Comment by saxofon** [comment]
OK from my side too.

**Comment by e-sailing** [comment]
👍 Agree.

**Comment by cmotelet** [comment]
👍 Agree.

**Comment by jlaba** [comment]
Agree as well

**Comment by multimike** [comment]
Agreed

**Comment by ph1l** [comment]
I'm confused..

So is there an example of the "small, perceived" licensing issues?

This changes the license from an open source copyleft license, which preserves our right to benefit from others (including corporations) modifying the code in the future, to a "do whatever you want" and profit off of the project without requiring to give back to the community license?

And this change, to the entire codebase, fixes one issue with one file used by one project?

:-1:

**Comment by sbender9** [comment]
@ph1l this decision was not about one project using one file. Where did you get that impression?

**Comment by ph1l** [comment]
> I want to change the license for (at least) the JSON file

**Comment by sbender9** [comment]
Yes, that was how this discussion got started, but it goes much deeper than that. The GPL (arguably) would not effect anyone using that file anyway since it is not "linked" into any applications. IMHO the GPL is not relevant anymore and it's not policeable or enforceable by small open source projects like ours. We're not going to be suing anyone over this stuff, that costs money.

There are small companies using this stuff, it's not the big guys. I think that's a good thing and I'd prefer that they didn't have worry about these legal issues. 

I want entrepreneurs to be able to innovate, create great products, and employ people.

**Comment by sbender9** [comment]
And you say "preserves our right to benefit from others"? You have three tiny commits. Good luck with that.

**Comment by keesverruijt** [comment]
Hi Phil, this is not a discussion on whether this license will be applied or not. I have carefully weighed the disadvantages and advantages.

The single file you talk about is the real meat of the project: the reverse-engineered NMEA and private PGN layout. The rest is totally boring C code that can easily be rewritten from scratch. 

The people we are restraining with the license are the small fledgling businesses that are interested in NMEA2000 and would like to get started with a small leg up before they invest in the NMEA membership and license fees. I have no issue with them starting with our code. They have to move up to NMEA membership if they want to certify NMEA 2000 compatibility anyway.

So the decision was made to go forward with this, to great acclaim from all contributors so far. If you really don't want to, I will revert your 3 commits (that do not involve the PGN list anyway.)

**Comment by keesverruijt** [comment]
Note that the other negative vote on the initial post in this issue from @vcaputo is from a non-contributor who collaborated on a different project with @ph1l ( https://github.com/vcaputo/rototiller ).

**Comment by vcaputo** [comment]
> Note that the other negative vote on the initial post in this issue from @vcaputo is from a non-contributor who collaborated on a different project with @ph1l ( https://github.com/vcaputo/rototiller ).

Perhaps I'm misreading, that comes across as negative and conspiratorial, which is surprising.  But then again, this is basically the twitter of software development.

@ph1l  and I are friends and frequent Libre-software collaborators.

I'm not a copyright holder of any code in this project, but @ph1l and I have discussed these subjects at length when sailing or reviewing/testing code outside of github (e-mail, IRC) over the years.  We've collaborated on more than just rototiller.  I have no legal basis to argue license changes here, but socially speaking, I do have an opinion.  And this being github, you're essentially inviting it.

**Comment by keesverruijt** [comment]
> Perhaps I'm misreading, that comes across as negative and conspiratorial, which is surprising. But then again, this is basically the twitter of software development.

Sorry? Github like Twitter? I guess your opinion is clear...

> I'm not a copyright holder of any code in this project, but @ph1l and I have discussed these subjects at length when sailing or reviewing/testing code outside of github (e-mail, IRC) over the years. We've collaborated on more than just rototiller. I have no legal basis to argue license changes here, but socially speaking, I do have an opinion. 

I am more than happy to have you chime in, especially when this would be a discussion on the merits of different software licenses, but it is not. The die has been cast on that; the license _will_ change. I am asking collaborators whether they want their contributions to roll over into the Apache-licensed next version. If they don't, fine, it will be removed and, if essential, re-engineered by someone else.

> And this being github, you're essentially inviting it.

I asked _contributors_ to chime in whether they vote yes/no, and I also asked contributors to PM me with what I should do with their source if they do not agree to their contributions being Apache-licensed. My comment was intended to point out that we can disregard your negative vote as you are not a contributor. Sorry if that came across as negative. It certainly wasn't "conspirational". I also haven't heard from @phil what I should do with his contributions.

**Comment by phil** [comment]
I have no idea; and TBH, I'm probably not the right person to ask … maybe try @ph1l ?
