### ISSUE TITLE
makefile defaults to /usr/bin instead of /usr/local/bin, not installable on OS X

### ISSUE THREAD

**Issue by justme3001** [canboat/canboat#229]
I just wanted to build and install canboat on my OS X machine and ran into a small problem: contary to the description in the README, the makefile sets the installation path to /usr/bin instead of /usr/local/bin, due to System Integrity Protection installation is not even possible as root in OS X then.
`actisense-serial
cp: /usr/bin/actisense-serial: Operation not permitted`
After changing path to /usr/local/bin, make install ran without any problems - would it be possible to change that in general or was this introduced by purpose?

best regards,
justme

**Comment by keesverruijt** [comment]
Not on purpose, just more Linux (and Old OSX-before-macOS-before-it-became-a-nanny-OS) oriented. But you are right that /usr/local/bin is better.
