### ISSUE TITLE
@canboat/pgns on npmjs is Out Of Date

### ISSUE THREAD

**Issue by dbeckwith01** [canboat/canboat#249]
@canboat/pgns on npmjs is quite out of date at v1.4.1.  What is the mechanism to get the updated pgn.json file from canboat/canboat to the npm repo?

I wasn't sure if this was the best place to ask this question but the npmjs page says this is the repo for @canboat/pgns.

**Comment by keesverruijt** [comment]
@sbender9 ping, can you look at this?

**Comment by sbender9** [comment]
I think we can close it. 3 yrs old, don't even use pgns.json anymore.
