### ISSUE TITLE
pgns-v2.json has lookup table "value"s as string, not integer

### ISSUE THREAD

**Issue by meaning-matters** [canboat/canboat#282]
Thanks for the amazing 3.0.0 update!

The `"value"` fields in the new `"LookupEnumerations"` are strings, not integers.  This makes parsing the JSON harder than necessary.

For example: `{"name": "Global", "value":"0"},` should be `{"name": "Global", "value":0},`.

(Also, encoding integer values as string is inconsistent with how PGNs are encoded.  For example `"BitLength":160,` already has `160` as integer.)

**Comment by keesverruijt** [comment]
Good point, Cornelis. Will fix.

**Comment by keesverruijt** [comment]
If you have _any_ other comments on how the new JSON can be improved, let me know!

**Comment by keesverruijt** [comment]
I tested with JS where datatypes don't matter, but not every language is as lenient.

**Comment by meaning-matters** [comment]
The JSON format requires numbers to be without `"  "`.  Quoted numbers are strings.

JS is just being nice by not adhering to the JSON RFC.

https://www.ietf.org/rfc/rfc4627.txt

**Comment by tkurki** [comment]
Parsing JSON in js retains the type information, there's just automatic coercion to Number if you use the value that way. It is not always your friend (read: causes unexpected fails).

Anyway, numbers should be numbers in JSON, unrelated to how you parse & use the format.
