### ISSUE TITLE
Update ship types list according to ITU-R M.1371-5

### ISSUE THREAD

**Issue by meaning-matters** [canboat/canboat#294]
In all documentation I've seen, the first AIS hazard category is "category A", like the other three: B, C, and D.

Why does CanBoat use "carrying dangerous goods" instead?

**Comment by keesverruijt** [comment]
Hmm, well, I don't know the actual reference any more but I am sure I didn't invent it!

I just looked up ITU-R recommendation M.1371 version 5, the current one, and this has a section 3.3.2, on page 116. 

This states the following for second digits where the first digit is 2, 4, 6, 7, 8 or 9

 1 – Carrying DG, HS, or IMO hazard or pollutant category X
 2 – Carrying DG, HS, or IMO hazard or pollutant category Y 
 3 – Carrying DG, HS, or IMO hazard or pollutant category Z
 4 – Carrying DG, HS, or IMO hazard or pollutant category OS

with a note stating _NOTE 1 – The digits 1, 2, 3 and 4 reflecting categories X, Y, Z and OS formerly were categories A, B, C and D._

So I will interpret this bug as that the list should be updated according to this definitive source.

See https://www.itu.int/dms_pubrec/itu-r/rec/m/R-REC-M.1371-5-201402-I!!PDF-E.pdf
