### ISSUE TITLE
"Temperature" is abbreviated a few times as "Temp"

### ISSUE THREAD

**Issue by meaning-matters** [canboat/canboat#298]
Low priority 'issue', seen in JSON.

I found that the term "temperature" is written out fully in most places.

Yet I see 3 places in which it's abbreviated as "temp": `"Sea Temp High"`, `"Sea Temp Low"`, and `"Water Temp Sensor"`.

Might be nice to have these three occurrences aligned?

**Comment by keesverruijt** [comment]
Keep them coming. I will be addressing all of your comments in one fell swoop once I get #283 done.
