### ISSUE TITLE
Field type has changed for `PGNs[].Fields[].Match` in pgn JSON/XML 

### ISSUE THREAD

**Issue by aldas** [canboat/canboat#302]
Previously "PGNs -> Fields -> Match"  was always number. Now it has text for some cases. See here https://github.com/canboat/canboat/blame/4e2b06a417730dd5e2c9ac8865807542b42299b3/analyzer/analyzer-explain.c#L439 and https://github.com/canboat/canboat/blob/7ef83a4c8f91a444bc1b6c5debec0cb0096b7162/analyzer/pgns.json#L4269

This is problematic languages with strict types (ala Go) as your unmarshalling will be now broken as you can not unmarshal text into integer.

I propose omitting outputting that field in case there is no value.

**Comment by keesverruijt** [comment]
Oops, that is an unintended use of the field. It will be fixed in the issue #283 refactoring, different uses will get different fields.
