### ISSUE TITLE
unit conversion MWV msg

### ISSUE THREAD

**Issue by villalolo** [canboat/canboat#31]
Hello,

I have made the following change to transform m/s (n2k) to knots (N) in the 183 msg in the wind speed.

The format must be 000.0 to be read by Furuno

Line 235

    float m2n;

Line 249

    m2n = strtof(speed, NULL);
    m2n = m2n * 1.944;
    snprintf(speed,12, "%05.1f", m2n);
    .... 
    if (strcmp(reference, "True") == 0)
    {
    	nmea0183CreateMessage(msg183, src, "MWV,%s,T,%s,N,A", angle, speed);

_updated comment to indent code properly -- canboat_

**Comment by canboat** [comment]
Hi @villalolo, first hurdle done -- you're creating issues.

You're right the units should be translated from m/s to the unit indicated in the NMEA0183 sentence. As you can see this nmea0183 code is still a bit of a hack that isn't well tested.

**Comment by villalolo** [comment]
what you guys are doing is amazing ...
