### ISSUE TITLE
Electrical Power fields with offset -2 giga W or 4+ giga W large range are correct?

### ISSUE THREAD

**Issue by meaning-matters** [canboat/canboat#313]
While scrolling through the current 4.1 JSON, I noticed electrical power fields of 32 bits with an offset of -2000000000 (without `Resolution` or range values).  Others had `RangeMax` of 4294967293 with `Resolution` of 1.

It seems odd to me that 32-bit field is used with a resolution of 1 (either implicitly of explicitly) with an offset of -2 giga Watt or a range up to 4 giga Watt.

Is this correct?

**Comment by keesverruijt** [comment]
The offset is correct, but they should have a Range (-20000000000 .. +2294967295) and Resolution 1. Thanks for catching this. This is different from a normal 2’s complement 32 bit integer with range -2147483648 .. +2147483647.

These PGNs originate from ISO, so they are _weird_ (only place that Excess K notation is used, range is a little exorbitant for a yacht).

**Comment by keesverruijt** [comment]
Nononono the offset presence indicates the field is using excess k instead of 2’s complement. So the presence has meaning.

**Comment by meaning-matters** [comment]
Thanks.  Assuming this, like many many other things, was documented, where could I have read this?

**Comment by keesverruijt** [comment]
Getting passive aggressive? Remember it is not my fault that N2K is so complicated.

As it happens, I am explaining exactly this in the canboat.xml + xsl. Go to these pgns with an offset and click on the word ‘offset’. 

The presence of the offset field makes it show this link.

I am not the worlds best xml tooling expert, I think there is a tool (file type) that allows me to explain xml files more directly. Any help with this would be very much appreciated.

**Comment by meaning-matters** [comment]
No not passive aggressive at all.  I am pretty new to CanBoat and N2K.

I felt stupid being surprised to find out about Excess-K.  My first sentence was an attempt to kindly ask if there was a quick way to avoid more silliness from my side.

I truly appreciate the large amounts of references, documentation, and descriptions.

**Comment by keesverruijt** [comment]
See `canboat.xsd`.
