### ISSUE TITLE
Source name 01 02 not working

### ISSUE THREAD

**Issue by villalolo** [canboat/canboat#32]
Hello,

Is it possible to allow users to chose the name of the nmea msg source. For instance, my wind instrument appears as 01 in the nmea0183 msg. however, Maxi or Furno wont recognize the message. They are expecting a "WI" 
$01MWV should be $WIMWV....   I think for Garmn its $IIMWV....

$WIMWV,163.6,R,012.7,N,A*25 is actually working ... god I hate that Furno... !! :).

thanks a lot

**Comment by canboat** [comment]
`$II` is not Garmin specific, it is also what Raymarine devices output. It stands for Integrated Instrument.

I've fixed the code so it stays within spec -- which is to generate two alphabetical characters. Receivers SHOULD or even MUST accept other senders. Which it is is hard to say without access to the official standard.

If your Furuno device doesn't accept anything else but `$WI` I would do two things:

1. Create a bug report with Furuno.
2. Fork this repository and change it to send out `$WI`.

Unfortunately, I cannot have it send out `$WI` as it would lose the fact which device sent the information, and you might have two wind sensors. As I actually do, I need this information in the receiving application to further filter which wind sensor I want displayed.
