### ISSUE TITLE
Saturation of the NMEA0183 network

### ISSUE THREAD

**Issue by villalolo** [canboat/canboat#33]
Is it possible to limit the number message going out in time. the network 183 is working at 4800 bds, and saturates very easily. 
$WIMWV,156.8,R,016.08,N,A*08, is sent 10 time/sec = 32 x 10 x 10 = 3200 bds
For instance, a GPS can send once per second.

**Comment by canboat** [comment]
This is TCP/IP so where is the 4800 baud limit coming from?

**Comment by canboat** [comment]
Are you stuffing this data back onto a serial port into an actual NMEA0183 network?

**Comment by villalolo** [comment]
The nmea is 4800, I feed MWV to an autopilot, but it also receive data from GPS and Navsoftare (way points)

**Comment by villalolo** [comment]
The Message is going from RPi to Arduino who dispatch and filter then to serial port

**Comment by canboat** [comment]
How's that for turn around time?

**Comment by villalolo** [comment]
I can see 2 ways, either drop everything that comes up too early, either drop m-1 out of m msg...

**Comment by canboat** [comment]
I already put in a fix: if you set `--rate-limit` on the `n2kd` command-line it will only report a particular message type once a second.

**Comment by villalolo** [comment]
Man... this is great ! seriously ...

**Comment by canboat** [comment]
I've been putting off sending more NMEA0183 sentences, would it help you if it also sent out a GPS location?

**Comment by villalolo** [comment]
Personnaly, I only have one n2k instrument..... the wind data  ..... but I think the more NMEA message that program can do the best.
