### ISSUE TITLE
sample  129540.raw incomplete

### ISSUE THREAD

**Issue by inquestruss** [canboat/canboat#340]
The last repeating set is missing two bytes of the range residuals field, the status field (4 bits), and the reserved padding (4 bits). The analyzer tool doesn't complain. A correctly formed message should have 3 bytes for the non-repeating fields and 12 bytes per repeating set (so 18 satellites would require 216+3=219 bytes).

**Comment by keesverruijt** [comment]
Correct. I will add a warning by analyzer when the PGN is incomplete, e.g. a number of sets are promised by a count field but not present in the data as fix for #334.
