### ISSUE TITLE
Search engine optimisation, bookmarkability/addressability of the documentation

### ISSUE THREAD

**Issue by tkurki** [canboat/canboat#365]
While https://canboat.github.io/canboat/canboat.xml works pretty nicely for humans I don't think the content ends up in search engines because of the xml + xsl rendering method.

I think the ability to bookmark / share a url that takes you to a specific PGN would also be useful. Not sure if that can be achieved with xml + xsl, as even if we add anchors to the pgns they are not present initially when the browser loads the page.

**Comment by tkurki** [comment]
There are plenty of different kits for generating documentation as static html, just pick one that is stable and won't be gone in 12 months. GH Actions can render the static html on master commits and version releases.

**Comment by keesverruijt** [comment]
It is trivial to generate a HTML version with xslt.

**Comment by keesverruijt** [comment]
I just did some google searches, and you are right, no links to canboat.xml seem to come up.
