### ISSUE TITLE
Multiple 'NotAssigned' values.

### ISSUE THREAD

**Issue by fulup-bzh** [canboat/canboat#404]
I'm in the process of including canboat-n2k PGNS within our new Rust signaling service https://github.com/redpesk-labs/canbus-rs . 

In this integration process I fail including canboat DBC because for 'unknown' value it uses the same 'matching' multiple time, this for different value. This prevents implementing enums for values match. 

Independently of how smart or code is, it will away be possible to receive unsupported values from a sensor. Every Can parser have to support signal value with invalid mapping. As a result it is rare that defining value as "not assigned" is necessary.

Ex:  "not assigned" value defined with 3 values for the same message (extract from pgns.jsonc
```
ex: PGN:65288 Id:seatalkAlarm
              {"name": "not assigned", "value": 77},
              {"name": "not assigned", "value": 78},
              {"name": "not assigned", "value": 79},
```

My impression is that either those "not assigned" value should be simply removed from the definition, or alternatively  the parser could generate something generic like 'unset_77','unset_78',...

**Comment by keesverruijt** [comment]
I agree. These should be removed.

**Comment by fulup-bzh** [comment]
Thank you
