### ISSUE TITLE
J1939 support?

### ISSUE THREAD

**Issue by penguinland** [canboat/canboat#443]
Hi! I'm trying to use the J1939 functionality in this codebase, which looks like it was added in #430 by @g2griz. I see that `.in` and `.out` test files were added in that PR, but the Makefile in the test directory does not use those files when running tests. I've tried manually running `cat analyzer/tests/j1939-pgn-test.in | ./rel/linux-x86_64/analyzer-j1939`, but the program exits with an "Unknown message format" error. I've read through the `detectFormat()` function, and agree with it that the data in the test file appears to be an unknown message format. It looks to me as though the code in that PR cannot parse the test files in that PR. The frustrating part is that I can get data from my own CAN that looks just like the test file: if I could analyze `j1939-pgn-test.in`, I could analyze the data I have, too!

Do you have any suggestions of what else I should try? I can't tell if I'm missing some code that was not included in PR #430 , or I'm misusing something else that is present but I don't recognize it.

Thanks for your time, and thanks so much for maintaining this repo!

**Comment by g2griz** [comment]
Thanks for the note.  Happy to see someone else using this capability.

The test.in file is in candump format.  You'll need to run it through candump2analyzer before sending it to analyzer (or analyzer-j1939 in this case).  So the command line would look like this if run from the makefile build directory:

pi@openplotter:~/canboat/rel/linux-aarch64 $ candump2analyzer <../../analyzer/tests/j1939-pgn-test.in | ./analyzer-j1939

I will update the makefile to incorporate the test functionality. Probably be a few days...

Please let me know if you have other questions.

**Comment by penguinland** [comment]
Yes, that works! Sorry I've made such a newbie mistake, and thanks for your patience setting me straight.
