### ISSUE TITLE
Compile error on "replay" binary

### ISSUE THREAD

**Issue by speters** [canboat/canboat#452]
Durig compilation of the "_replay_" binary, I get the following error:
```
/canboat-git/src/canboat/replay   makepkg  LANG=C make
cc  -Wall -O2  -o ../rel/linux-x86_64/replay -I../common replay.c ../common/common.c
replay.c: In function 'main':
replay.c:69:9: error: implicit declaration of function 'strptime'; did you mean 'strftime'? [-Wimplicit-function-declaration]
   69 |     r = strptime(line, FORMAT_DT, &tm);
      |         ^~~~~~~~
      |         strftime
replay.c:69:7: error: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
   69 |     r = strptime(line, FORMAT_DT, &tm);
      |       ^
make: *** [Makefile:33: ../rel/linux-x86_64/replay] Error 1
```

As the "_socketcan-writer_" also uses _strptime()_ and compiles flawlessly, I looked into it and found that it defined `_GNU_SOURCE`.

So I patched the `replay/Makefile`:
```patch
diff --git i/replay/replay.c w/replay/replay.c
index fdafb11..f180072 100644
--- i/replay/replay.c
+++ w/replay/replay.c
@@ -23,6 +23,7 @@ limitations under the License.

 */

+#define _GNU_SOURCE
 #include <stdbool.h>
 #include <stdio.h>
 #include <stdlib.h>
```

This seems to fix it.

PS:
There still is a minor issue with the man-page generation not working as expected, but I had not figured out yet if it is a problem within my ARCHlinux installation.

**Comment by anm** [comment]
I don't know if it is a good solution, but you can get it to build by adding this to the start of the file:
`#define _GNU_SOURCE`

It is used in another part of the code too.

**Comment by keesverruijt** [comment]
According to the man page of strptime() it requires _XOPEN_SOURCE, so I'm using that. I trust this will work on ARCH Linux as well.

**Comment by keesverruijt** [comment]
See https://www.man7.org/linux/man-pages/man3/strptime.3.html
