### ISSUE TITLE
Documentation - Provide "Change Log" or "Last Updated"(Date)

### ISSUE THREAD

**Issue by jeokeefe** [canboat/canboat#459]
The PGN documentation provided at https://canboat.github.io/canboat/canboat is excellent. It would be great to be able to follow changes from version to version. Even in the simplest form a "Last Modified." value on the entries would be great. Please consider doing this.

**Comment by acolomb** [comment]
The info is generated from this source repository.  You can see the full log of all changes committed to Git here: https://github.com/canboat/canboat/commits/master/docs
