### ISSUE TITLE
definitions with incorrect length data

### ISSUE THREAD

**Issue by inquestruss** [canboat/canboat#461]
These both exceed the maximum fast packet size of 233 bytes:

From the documentation page:
0x1F608: PGN 128520 - Tracked Target Data
This fast-packet PGN is 248 bytes long and contains 15 fields. 
Name field is defined as 1784 bits; should be maximum of 1664 (including string fix overhead)

0x1FF05: PGN 130821 - Navico: ASCII Data
This fast-packet PGN is 259 bytes long and contains 5 fields. 
--Message field is defined as 2048 bits; should be maximum of 1840 (including string fix overhead)

**Comment by keesverruijt** [comment]
Hmmm, yes, the field lengths are just copied from the AIS specification. If they are transmitted as fast packets, and I think so, then the limits are indeed smaller.

I will assume that they are indeed sent as fast packets.
