### ISSUE TITLE
Remove Unicode characters in canboat.json and canboat.xml

### ISSUE THREAD

**Issue by keesverruijt** [canboat/canboat#468]
I have found that docs/canboat.json line 15946 contains invalid JSON.  The string value for "Explanation" contains multiple unescaped " characters within the quoted string.
I have patched this within my copy but you will want to fix this.

_Originally posted by @antipole2 in https://github.com/canboat/canboat/issues/462#issuecomment-2560744165_

**Comment by keesverruijt** [comment]
@antipole2 the characters that you refer to are "curly" double quotes, not normal ASCII double quotes. So the validator which we run during the build (by reading everything into Python) doesn't see this as breaking any contract, and strictly spoken it is right.

However, I feel that UNICODE characters in the explanation needlessly complicate matters as it requires all downstream users to support UTF-8, so I will remove them.

**Comment by antipole2** [comment]
Thanks.
I am parsing using the DukTape JavaScript engine, which only parses ASCII, at least on Windows.

**Comment by keesverruijt** [comment]
According to the DukTape documentation it supports UTF-8, but the point stands.

**Comment by keesverruijt** [comment]
Some other non-ASCII characters found as well.

Fixing this and adding a test so this cannot regress.
