### ISSUE TITLE
Bluetooth Support

### ISSUE THREAD

**Issue by kidturbo** [canboat/canboat#47]
Hi all, 
wondering if anyone might be interested in coding an API for BLE modem support into canboat. Have a new can/can gateway that we've developed specifically to translate "uncommon" ECM/PCM messages into N2k PGN sets for display on plotter/gauge. We included a BT 4.0 modem in the hardware design, but haven't had any time to work on additional software support. The rest of it works great, and it provides a direct unmolested SPI or UART line onto the NMEA bus. So figured this might be of some interest to the canboat community. Let me know if interested at taking a look.

-K

**Comment by canboat** [comment]
Isn't a bluetooth transport just a serial port, i.e. stream of bytes?
