### ISSUE TITLE
not all release artifacts are created on release

### ISSUE THREAD

**Issue by aldas** [canboat/canboat#470]
https://github.com/canboat/canboat/actions/runs/12495099793/job/34865489144

> Run export CANBOAT_VERSION=$(sed -En 's/.*\ VERSION\ \"([0-9]+\.)([0-9]+\.)?([0-9]+)\"/\1\2\3/p' common/version.h)
Checking if docs/canboat.json contains "CANboat version v5.1.2"
Error: Process completed with exit code 1.

so pgn files are not added to release.

last working release was https://github.com/canboat/canboat/releases/tag/v5.1.0 which had 6 files

**Comment by keesverruijt** [comment]
Good catch! I didn't even notice. Updated my workflow slightly so this is not likely to occur again. Fixed in v5.1.3.

**Comment by aldas** [comment]
@keesverruijt I think there is setting somewhere that will make Github to email you when actions fail.  I think this
https://docs.github.com/en/account-and-profile/managing-subscriptions-and-notifications-on-github/setting-up-notifications/configuring-notifications#github-actions-notification-options

I use this for my own repos/maintained projects
