### ISSUE TITLE
129540 Satellites in view: use array?

### ISSUE THREAD

**Issue by tkurki** [canboat/canboat#55]
JSON output for 129540 looks like n times
```
    "PRN XX": "67",
    "Elevation XX": "41.0",
    "Azimuth XX": "207.0",
    "SNR XX": "31.00",
    "Range residuals XX": "0",
    "Status XX": "Used"
```

How about making the satellites' details an array?

**Comment by tkurki** [comment]
Related: https://github.com/SignalK/n2k-signalk/issues/12

**Comment by tkurki** [comment]
See also https://github.com/SignalK/specification/issues/163#issuecomment-183304174

**Comment by tkurki** [comment]
Almost: the array is a property and needs a name: 

```
  "fields": {
    "SID": 207,
    "Sats in View": 11,
    [{
      "PRN": 32,
      "Elevation": 69.0,
      "Azimuth": 223.0,
      "SNR": 32.00,
```

**Comment by canboat** [comment]
Do you think I should put a name for the array in the datamodel so that it says `"satellites":` for this PGN or can I get away with `"list": ` ?

**Comment by canboat** [comment]
(or something else instead of list?)
