### ISSUE TITLE
Not able to log candump2analyzer output to a logfile

### ISSUE THREAD

**Issue by Mehul2802** [canboat/canboat#64]
Hi,

I am sending wind station data on vcan0 interface.
![selection_004](https://cloud.githubusercontent.com/assets/7879392/15389886/af26033c-1dd6-11e6-85fb-eff54b38d8f7.png)
![selection_005](https://cloud.githubusercontent.com/assets/7879392/15389903/bc21f172-1dd6-11e6-91ad-1ffd615ba69d.png)
This works fine when I am not using redirection.

However, when I use command
![selection_006](https://cloud.githubusercontent.com/assets/7879392/15389934/ddb7127c-1dd6-11e6-88d6-1f76dfb94ded.png)

I didn't get a log in the specified file.

Regards,
Mehul

**Comment by JohanElmis** [comment]
Hi,

I was amazed by that shocking article  I've  recenly read,  please read it and tell  me your opinion  <http://light.suessite.com/e4ems>

See you soon, johan@elmerfjord.com
