### ISSUE TITLE
N2KD's JSON caching port...

### ISSUE THREAD

**Issue by woobagooba** [canboat/canboat#7]
Thanks much for the expanded information in N2KD's wiki page.  Its now apparent ...  different app layer data items can be received within different instances of same PGN from the same address.  So just saving the last PGN from any address will mean app layer data is lost.  This smells like a deficiency in the PGN design ... but it is what it is.

So now I'm wondering about an alternative to the JSON caching port format.  Something like the following ....

<app data item name><app data item value><PGN from which it was acquired><src address of the PGN transmitter><timestamp>

So instead of this...

```json
 {   "130311": 
    {"description":"Environmental Parameters","35_Sea": {"timestamp":"2012-11-22-12:24:03.000","prio":"5","src":"35","dst":"255","pgn":"130311","description":"Environmental Parameters","fields":{"SID":"31","Temperature Instance":"Sea","Temperature":"19.44"}}
    }
 }
```

JSON caching port returns this...

```json
{   
	"Sea Temperature": "67.5"
	"PNG" : "130311"
	"src":"35"
	"timestamp":"2012-11-22-12:24:03.000"
}
```

This would allow the app to just drag the name and value for display etc

With enough info left over to allow correlation with the JSON streaming port (if needed).

Thoughts?

**Comment by stevepmitchell** [comment]
Is your web app/page something that you have released to the public?  This is exactly the same path I have been on for several years, but never got around to finishing it...

**Comment by tkurki** [comment]
@stevepmitchell The activity has swifted to things related to SignalK, see
* http://signalk.org/
* https://github.com/SignalK/
* https://github.com/SignalK/sailgauge
* https://github.com/SignalK/instrumentpanel

**Comment by canboat** [comment]
Closing as Signal K will be the focus of new development.
