### ISSUE TITLE
n2kd servers should return HTTP compliant repsonse or not?

### ISSUE THREAD

**Issue by jlaba** [canboat/canboat#84]
Currently n2kd just returns the json values. This may (and e.g. with python requests module it does) lead to problems consuming the page, using standard compliant clients.

So my question is, should n2kd servers return a HTTP compliant response or not? If yes, I'm try to implement it.

See http://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html for what a compliant response should contain.

**Comment by woobagooba** [comment]
Do you mean an HTTP compliant Response body, or a full RESTful interface?


________________________________

**Comment by canboat** [comment]
n2kd server is a minimal C program that does NOT implement HTTP. At all. Period. It uses its own minimal protocol, which is suited to a frontend that implements HTTP.

I know RFC2616 (superceded by RFC7230) back-to-front and implementing it from scratch is a lot of work.

**Comment by canboat** [comment]
If somebody wants to invest the time and write up a simple HTTP server, or a small wedge between (for instance) NGINX and n2kd I'd be more than happy to integrate your pull request :-)

**Comment by jlaba** [comment]
Maybe https://www.gnu.org/software/libmicrohttpd/ is a useful library to use as http server within this project. It seems to be very small, powerful enough and is implemented in C.

Might this be an option for you?

**Comment by tkurki** [comment]
@jlaba are you aware of https://github.com/SignalK/signalk-server-node ?

Embeds canboat, data over http(s) and websocket and tcp, data from nmea2000 and nmea0183 in uniform format, conversions to nmea0183 etc.

**Comment by jlaba** [comment]
Thanks for the hint!

Seems to be very interesting. As I understood Node Js 6 is needed and since my 
goal is to install everything from packages (therefore I packaged n2kd) I will 
have a deeper look at signalK after the first release of my project ;-)

**Comment by tkurki** [comment]
See also https://github.com/tkurki/marinepi-provisioning

**Comment by jlaba** [comment]
Your one step ahead ;-) But my puppet module is also ready now.
