### ISSUE TITLE
Rate-of-Turn resolution

### ISSUE THREAD

**Issue by jkuszmaul** [canboat/canboat#96]
It appears that the resolution for the rate-of-turn message (PGN 127251) as
supplied in this repository (3.125e-9) is incorrect and off by a factor of ten (it should be 3.125e-8).

I noticed this by differentiating (and slightly smoothing, to make it displayable) the heading data and
comparing it to the rate of turn data. In order to get the two to match, I had to divide the speeds
as derived from the heading data by 10 to get them to match the rate of turn. Because the
rate of turn and heading data are both coming in at 10Hz, it does not seem unreasonable to
assume that there is something particular about a factor of 10 that is causing confusion somewhere,
hence my inclination to believe that the error is exactly a factor of 10 (in fact, I originally erred
and plotted my differentiated heading data without dividing by the 0.1sec dt and so ended
up with the Airmar rate of turn and differentiated data matching perfectly).

Am I missing something obvious, is this a known issue, or is this worth checking further?

I don't have any raw candumps on-hand, although they are easy to get. It is certainly possible
that there is some error in my processing (I log after processing the raw CAN messages),
although given that the heading data and everything else I use is fine, that seems unlikely.

See below for some data, from the Airmar 220WX that I'm using to collect data, in which I
adjust by the factor of 10 and the data matches up reasonably.

![airmar_omega](https://user-images.githubusercontent.com/4754043/33028462-071e4572-cde4-11e7-9467-0cf89e0be635.png)

**Comment by canboat** [comment]
Hi J, this certainly makes sense. There is only 1 field that uses high resolution rotation, so this was just a guess on my part and nobody ever challenged it. I just went back to a log file I made in 2011 and you are absolutely correct.
