### ISSUE TITLE
Cannot derive variable length error

### ISSUE THREAD

**Issue by jeffmc640** [canboat/canboat#99]
@canboat Hello... I'm receiving the following error contained in the attached log file snippet.  Can someone please let me know if there's anything that can be done to resolve this error.

Thanks in advance,
-jeff-
[syslog.txt.copy.txt](https://github.com/canboat/canboat/files/1556435/syslog.txt.copy.txt)

**Comment by keesverruijt** [comment]
Assuming this is fixed in the current release.
